apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
  labels:
    app: polling-app
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: polling-app-postgresql
  labels:
    app: polling-app
spec:
  ports:
    - port: 5432
  selector:
    app: polling-app
    tier: postgresql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polling-app-postgresql
  labels:
    app: polling-app
spec:
  selector:
    matchLabels:
      app: polling-app
      tier: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: polling-app
        tier: postgresql
    spec:
      containers:
      - image: postgres:15
        name: postgresql
        env:
        - name: POSTGRESQL_ROOT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: postgresql-root-pass
              key: password
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgresql-db-url
              key: database
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-user-pass
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-user-pass
              key: password
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: postgresql-persistent-storage
          mountPath: /var/lib/postgresql
      volumes: 
      - name: postgresql-persistent-storage
        persistentVolumeClaim:
          claimName: postgresql-pv-claim